version: '3.9'

services:
    database-service:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8010
        volumes:
            - ../backend/:/usr/src/app/
        ports:
            - "8002:8010"
        env_file:
            - ../.env
        networks:
            - almacen-network
        restart: on-failure

    almacen-postgres-db:
      build:
        context: ../config_db
        dockerfile: Dockerfile
      volumes:
        - ../db/almacen-postgres-data:/var/lib/postgresql/data
      env_file:
        - ../.env
      ports:
        - "5433:5432"
      networks:
        - almacen-network

networks:
    almacen-network:
        external: True